### ISSUE TITLE
Missing install instructions in readme (peer dependencies)

### ISSUE THREAD

**Issue by rorykoehein** [kristw/react-vega-lite#3]
It might be nice to add the prerequisites to the installation instructions (peer dependencies and peer dependencies' peer dependencies).

After adding react-vega-lite to my project, I encountered an error, which lead me to check the peer dependencies of the project in the package.json and install them. Then I got another error, which lead me to checking the peer dependencies of `react-vega` to install `vega`.

I'm happy to do a PR if you agree. Thanks!

**Comment by kristw** [comment]
PR is welcome :)

**Comment by kristw** [comment]
I have updated the readme.

**Comment by rorykoehein** [comment]
Awesome. Got a bit time crunched over here...
